[tool.pylint.messages_control]
disable = [
    "invalid-name",
    "missing-function-docstring",
    "missing-module-docstring",
    "duplicate-code"
]

[tool.black]
line-length=100
target-version=["py38"]